# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on: [push]

env:
  IMAGE_NAME: quiz-backend

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
#         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#         settings-path: ${{ github.workspace }} # location for the settings.xml file
        
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Build a container image from our Spring Boot app using Paketo.io / Cloud Native Build Packs
      run: mvn spring-boot:build-image -Dspring-boot.build-image.imageName=$IMAGE_NAME

    - name: Publish to GitHub Packages Apache Maven
      run: |
        docker tag $IMAGE_NAME ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
        docker push ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME:latest
      env:
        GITHUB_TOKEN: ${{ github.token }}
